//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excavation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excavation()
        {
            this.ExcavationsPublications = new HashSet<ExcavationsPublication>();
            this.Findings = new HashSet<Finding>();
            this.ResearchersExcavations = new HashSet<ResearchersExcavation>();
        }
    
        public int excavationID { get; set; }
        public Nullable<int> siteID { get; set; }
        public Nullable<System.DateTime> excavationDate { get; set; }
        public Nullable<int> areaID { get; set; }
        public string excavationSize { get; set; }
        public string comment { get; set; }
        public string bibliography { get; set; }
        public string excavationHeb { get; set; }
        public string excavationEng { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Site Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcavationsPublication> ExcavationsPublications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finding> Findings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchersExcavation> ResearchersExcavations { get; set; }
    }
}
