//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Finding()
        {
            this.FindingsPeriods = new HashSet<FindingsPeriod>();
        }
    
        public int findingID { get; set; }
        public string descriptionEng { get; set; }
        public string descriptionHeb { get; set; }
        public int findingTypeID { get; set; }
        public int siteTypeID { get; set; }
        public int siteNatureID { get; set; }
        public string findingDate { get; set; }
        public int excavationID { get; set; }
    
        public virtual Excavation Excavation { get; set; }
        public virtual SiteNature SiteNature { get; set; }
        public virtual SiteType SiteType { get; set; }
        public virtual FindingType FindingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindingsPeriod> FindingsPeriods { get; set; }
    }
}
