//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindingsPeriod
    {
        public int findingPeriodID { get; set; }
        public int findingID { get; set; }
        public int periodID { get; set; }
    
        public virtual Finding Finding { get; set; }
        public virtual Period Period { get; set; }
    }
}
