//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationAPIResult
    {
        public int siteID { get; set; }
        public string coordinateSource { get; set; }
        public Nullable<double> locationiqLon { get; set; }
        public Nullable<double> locationiqLat { get; set; }
        public Nullable<double> googleLat { get; set; }
        public Nullable<double> googleLon { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
