//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.AuthorsPublications = new HashSet<AuthorsPublication>();
            this.ExcavationsPublications = new HashSet<ExcavationsPublication>();
        }
    
        public int publicationID { get; set; }
        public string articleTitle { get; set; }
        public string year { get; set; }
        public Nullable<int> periodicalID { get; set; }
        public string bibliography { get; set; }
        public string URL { get; set; }
        public string FDFName { get; set; }
        public Nullable<int> publicationTypeID { get; set; }
        public string abstractEng { get; set; }
        public string abstractHeb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorsPublication> AuthorsPublications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcavationsPublication> ExcavationsPublications { get; set; }
        public virtual Periodical Periodical { get; set; }
        public virtual PublicationType PublicationType { get; set; }
    }
}
