//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitesPeriod
    {
        public int sitesPeriodsID { get; set; }
        public int siteID { get; set; }
        public int periodID { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Site Site { get; set; }
    }
}
