//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitesSiteName
    {
        public int sitesSiteNamesID { get; set; }
        public int siteID { get; set; }
        public int siteNameID { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual SitesName SitesName { get; set; }
    }
}
