//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.Excavations = new HashSet<Excavation>();
            this.SitesPeriods = new HashSet<SitesPeriod>();
            this.SitesSiteNames = new HashSet<SitesSiteName>();
        }
    
        public int siteID { get; set; }
        public Nullable<double> LabelX { get; set; }
        public Nullable<double> LabelY { get; set; }
        public string NIG_Info { get; set; }
        public System.Data.Entity.Spatial.DbGeography WGS84_Info { get; set; }
        public string siteSize { get; set; }
        public Nullable<int> oldSiteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Excavation> Excavations { get; set; }
        public virtual LocationAPIResult LocationAPIResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitesPeriod> SitesPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitesSiteName> SitesSiteNames { get; set; }
    }
}
