//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceDBConnection
    {
        public int ID { get; set; }
        public Nullable<int> sourceID { get; set; }
        public Nullable<int> dbID { get; set; }
        public Nullable<int> tableID { get; set; }
    
        public virtual RecordSource RecordSource { get; set; }
        public virtual TableCode TableCode { get; set; }
    }
}
